### PR TITLE
Dropdown: Popper migration to floating-ui

### LINKED ISSUE #4207: DropdownMenu positioning + Buttons
Noted on Blazorise Support app that **DropdownMenu** was not working correctly with Buttons.

Investigate further, example code:
image

Example bug:
image

### LINKED ISSUE #4690: Dropdown-menu opening position.
**Describe the bug**
When using and opening the DropDown component the DropDownMenu is not positioned correctly

**To Reproduce**
Open the attached example project. 

**Expected behavior**
The position of the dropdown-menu should be aligned under the button.

Also please provide a sample code or point us to a minimalistic GitHub repo

**Screenshots**
image

**Additional context**
I have added a little example project here to demonstrate the problem .
[BlazoriseIssues.zip](https://github.com/Megabit/Blazorise/files/11045168/BlazoriseIssues.zip)

### LINKED ISSUE #4884: Dropdown: control the position strategy
In our `dropdown.js`, we have the `strategy: "fixed"` strongly typed. We need to add an option to define

- `absolute`, and
- `fixed`

```
const instance = createPopper(targetElement, menuElement, {
    placement: getPopperDirection(options.direction, options.rightAligned),
    strategy: "fixed",
    modifiers: [
        {
            name: "preventOverflow",
            enabled: true,
            options: {
                padding: 0,
            }
        }
    ]
});
```

Docs: https://popper.js.org/docs/v2/constructors/#strategy

### LINKED ISSUE #4885: Migrate PopperJS to new library
It seems that popperJS have become obsolete https://github.com/floating-ui/floating-ui/issues/2386#issuecomment-1596447265

We need to think of moving to the new version 

The migration to the new library on https://floating-ui.com/docs/migration

### PR DESCRIPTION
**Pull request by David-Moreira**
Closes #4885
Closes #4884 

---

**Buttons inside the dropdown related issues fixed:**
Closes #4690
Closes #4207

### CODE REVIEW

File: Source/Blazorise/Enums/FloatingPositionStrategy.cs [hunk 1]
```diff
@@ -0,0 +1,17 @@
+﻿namespace Blazorise.Enums;
+
+/// <summary>
+/// Defines the position strategy for the floating component.
+/// <para>See : https://floating-ui.com/docs/computeposition#strategy</para>
+/// </summary>
+public enum FloatingPositionStrategy
```
Comment (stsrki) [inline Source/Blazorise/Enums/FloatingPositionStrategy.cs:7]: I would name this DropdownMenuPositionStrategy, or DropdownPositionStrategy as it is used only on the Dropdown.

File: Source/Blazorise/Styles/_floating-ui.scss [hunk 2]
```diff
@@ -0,0 +1,13 @@
+.floating {
```
Comment (stsrki) [inline Source/Blazorise/Styles/_floating-ui.scss:1]: add a prefix

```suggestion
.b-floating {
```

File: Source/Blazorise/Styles/blazorise.scss [hunk 3]
```diff
@@ -32,3 +32,4 @@
 
 @import "vendor/flatpickr";
 @import "vendor/colorpicker";
+@import "floating-ui";
```
Comment (stsrki) [inline Source/Blazorise/Styles/blazorise.scss:35]: Move it under the `vendor` folder.

File: Source/Blazorise/Enums/FloatingPositionStrategy.cs (hunk 1 above)
Comment (David-Moreira) [reply Source/Blazorise/Enums/FloatingPositionStrategy.cs:7]: This way it's future proof though.
I don't quite remember, but don't we have something else using it? tooltips?

Comment (David-Moreira) [reply Source/Blazorise/Enums/FloatingPositionStrategy.cs:7]: I guess you're right. I'll change it. In the future if we need to use elsewhere, we can just do a copy paste for naming sake

**Comment by David-Moreira** [comment]
@stsrki so far so good except the `Direction.Up`, it has a strange behaviour, don't know why this one is different, any idea?
image

**Comment by David-Moreira** [comment]
> @stsrki so far so good except the `Direction.Up`, it has a strange behaviour, don't know why this one is different, any idea? image

Nevermind, fixed for bootstrap, gotta check other providers.

Remember the issue I told you about with the buttons inside the dropdown, might be because of this detection:
image
I believe that's for this feature:
image
We'll have to figure out a workaround.

File: Source/Blazorise/wwwroot/dropdown.js [hunk 4]
```diff
@@ -1,30 +1,8 @@
 import { getRequiredElement } from "./utilities.js?v=1.2.4.0";
-import { createPopper } from "./popper.js?v=1.2.4.0";
-import { createAttributesObserver, observeClassChanged, destroyObserver } from "./observer.js?v=1.2.4.0";
+import { createFloatingUiAutoUpdate } from './floatingUi.js?v=1.2.4.0';
```
Comment (stsrki) [inline Source/Blazorise/wwwroot/dropdown.js:2]: Dont forget to update version `v=1.3.0.0`

File: Source/Blazorise/wwwroot/floatingUi.js [hunk 5]
```diff
@@ -0,0 +1,40 @@
+import { computePosition, autoUpdate, flip, shift, limitShift } from './vendors/floating-ui.js?v=1.2.4.0';
```
Comment (stsrki) [inline Source/Blazorise/wwwroot/floatingUi.js:1]: Also update version.

**Comment by David-Moreira** [comment]
> > @stsrki so far so good except the `Direction.Up`, it has a strange behaviour, don't know why this one is different, any idea? image
> 
> Nevermind, fixed for bootstrap, gotta check other providers.
> 
> Remember the issue I told you about with the buttons inside the dropdown, might be because of this detection: image I believe that's for this feature: image We'll have to figure out a workaround.

Like we've talked fixed the issue by making it a fallback only if no dropdown toggles are defined.

File: Documentation/Blazorise.Docs/Pages/Docs/Helpers/Enums/DropdownPage.razor [hunk 6]
```diff
@@ -1,9 +1,9 @@
-﻿@page "/docs/helpers/enums/dropdown"
+﻿D@page "/docs/helpers/enums/dropdown"
 
 <Seo Canonical="/docs/helpers/enums/dropdown" Title="Enums: Dropdown" Description="Learn to use and work with the Blazorise Dropdown enums that help you to modify the dropdowns appearance and their behavior." />
 
 <DocsPageTitle>
-    Enums: Dropdown
+    Enums: DropdownD
```
Comment (stsrki) [inline Documentation/Blazorise.Docs/Pages/Docs/Helpers/Enums/DropdownPage.razor:6]: Small typo.

File: Documentation/Blazorise.Docs/Pages/Docs/Helpers/Enums/DropdownPage.razor [hunk 7]
```diff
@@ -1,9 +1,9 @@
-﻿@page "/docs/helpers/enums/dropdown"
+﻿D@page "/docs/helpers/enums/dropdown"
```
Comment (stsrki) [inline Documentation/Blazorise.Docs/Pages/Docs/Helpers/Enums/DropdownPage.razor:1]: Extra `D` here.

File: Source/Blazorise/Interfaces/IClassProvider.cs [hunk 8]
```diff
@@ -408,6 +409,8 @@ public interface IClassProvider
 
     string DropdownHeader();
 
+    string DropdownMenuFloating( DropdownPositionStrategy dropdownPositionStrategy );
```
Comment (stsrki) [inline Source/Blazorise/Interfaces/IClassProvider.cs:412]: Rename `DropdownMenuFloating` to `DropdownMenuPositionStrategy`.

File: Source/Blazorise/Styles/vendor/_floating-ui.scss [hunk 9]
```diff
@@ -0,0 +1,13 @@
+.b-floating {
```
Comment (stsrki) [inline Source/Blazorise/Styles/vendor/_floating-ui.scss:1]: TBH, I don't like this `floating` name. Can we find an alternative?

- `position-strategy`, or
- `dropdown-position-strategy`, or
- `dropdown-menu-position-strategy`

---

I would go even further. Create new classes for each of CSS providers so that names match their convention.

AntDesign:  `and-dropdown-menu-position-strategy and-dropdown-menu-position-strategy-{type here}`
Bootstrap:  `dropdown-menu-position-strategy dropdown-menu-position-strategy-{type here}`
Tailwind:  `max-w-max top-0 left-0 fixed`, or `max-w-max top-0 left-0 absolute`

Comment (David-Moreira) [reply Source/Blazorise/Styles/vendor/_floating-ui.scss:1]: I guess I wanted it to be representative of the feature so you can easily associate it with the floating-ui lib. I don't mind the suggestions, will go ahead with the suggested changes.

File: Documentation/Blazorise.Docs/Pages/Docs/Helpers/Enums/DropdownPage.razor (hunk 6 above)
Comment (David-Moreira) [reply Documentation/Blazorise.Docs/Pages/Docs/Helpers/Enums/DropdownPage.razor:6]: Damn, how did those get in there haha

File: Source/Blazorise/Styles/vendor/_floating-ui.scss (hunk 9 above)
Comment (stsrki) [reply Source/Blazorise/Styles/vendor/_floating-ui.scss:1]: Yeah, but we also want to abstract it away from the library.

**Comment by stsrki** [comment]
I'm trying the BS5 demo, and the example for the Split dropdown button doesn't work correctly. See an image

image

The menu should start bellow the dropdown.

**Comment by stsrki** [comment]
On further investigation, it seems that is how BS5 is now working. Stange 🤔

image

**Comment by David-Moreira** [comment]
> On further investigation, it seems that is how BS5 is now working. Stange 🤔
> 
> image

You are right, I was just looking at live blazorise demo and it opens up on the dropdown...

But on my tests I didn't even notice as it just felt correct. It's a menu button, and it just felt correct for the menu to open up with it as an anchor.
I actually believe this is correct, and would keep it, what do you think?

**Comment by stsrki** [comment]
> I actually believe this is correct, and would keep it, what do you think?

Yes, keep it. I can only assume that in the past it worked differently and they changed it in BS at some point.

**Review by stsrki — APPROVED** [review]
